### ISSUE TITLE
Homebridge Config

### ISSUE THREAD

**Issue by ixy05** [chrisw554/homebridge-web-garage-for-ESP8266#1]
Hello, 

Great work on this program. I was just wondering what your homebridge configuration file for the garage plugin looked like.

Thanks!

**Comment by chrisw554** [comment]
Hey there

I use the Homebridge UI to edit the config for the Plugin. Here's a snippet from my config file. 

 "accessories": [
        {
            "accessory": "GarageDoorOpener",
            "name": "Garage Door 2",
            "apiroute": "http://192.168.1.57"
        },
        {
            "accessory": "GarageDoorOpener",
            "name": "Garage Door 1",
            "apiroute": "http://192.168.1.66",
            "port": "2001"
        },

When no port is specified the default port 2000 is used

Hope that helps..!

**Comment by ixy05** [comment]
Thankyou!
